sudo: required
dist: focal
language: cpp

matrix:
  include:
    - compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gfortran
            - automake
            - perl
            - libboost-all-dev
            - zlib1g-dev
            - libbz2-dev
            - liblzma-dev
            - libpcre3-dev
            - libedit-dev
            - gcc
            - g++
      env: C_COMPILER=gcc CXX_COMPILER=g++ CFLAGS="-g -O1" CXXFLAGS="${CFLAGS}" LDFLAGS="${CFLAGS}"

    - compiler: clang
      addons:
        apt:
          sources:
            - sourceline: "deb http://llvm.org/apt/focal/ llvm-toolchain-focal-10 main"
          packages:
            - gfortran
            - automake
            - perl
            - libboost-all-dev
            - zlib1g-dev
            - libbz2-dev
            - liblzma-dev
            - libpcre3-dev
            - libedit-dev
            - libomp-10-dev
            - clang
            - llvm-dev
      env: C_COMPILER=clang CXX_COMPILER=clang++ LLVM_CONFIG=/usr/bin/llvm-config CFLAGS="-g -O1" CXXFLAGS="${CFLAGS}" MAIN_LDFLAGS="${CFLAGS}"
script:
        - ${CXX_COMPILER} --version
        - cd R
        - CC=${C_COMPILER} CXX=${CXX_COMPILER} ./configure --with-included-gettext --enable-R-profiling --enable-memory-profiling
        - travis_wait 60 make
          #- travis_wait 60 make check
