sudo: required
dist: bionic
language: c

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gfortran
            - automake
            - perl
            - libboost-all-dev
            - zlib1g-dev
            - libbz2-dev
            - liblzma-dev
            - libpcre2-dev
            - libedit-dev
            - gcc
            - g++
      env: C_COMPILER=gcc CXX_COMPILER=g++ CFLAGS="-g -O2" CXXFLAGS="${CFLAGS}" LDFLAGS="${CFLAGS}"

    - compiler: clang
      addons:
        apt:
          sources:
            - sourceline: "deb http://llvm.org/apt/bionic/ llvm-toolchain-bionic-10 main"
          packages:
            - gfortran
            - automake
            - perl
            - libboost-all-dev
            - zlib1g-dev
            - libbz2-dev
            - liblzma-dev
            - libpcre2-dev
            - libedit-dev
            - libomp-dev
            - clang
            - llvm-dev
      env: C_COMPILER=clang CXX_COMPILER=clang++ LLVM_CONFIG=/usr/bin/llvm-config CPPFLAGS="-DNO_CELLPOOLS" CFLAGS="-g -O2" CXXFLAGS="${CFLAGS}" MAIN_LDFLAGS="${CFLAGS}"
script:
        - cd R
        - CC=${C_COMPILER} CXX=${CXX_COMPILER} ./configure --with-included-gettext --enable-R-profiling --enable-memory-profiling
        - travis_wait 60 make
          #- travis_wait 60 make check
